### ISSUE TITLE
Proposal: Feedback

### ISSUE THREAD

**Issue by s-pangburn** [marshallycheng/Gameshelf#1]
### Homepage
- [x] Your links should be a bullet-pointed list, preferably with MVP List on top
- [x] Either change the title "Home" to "Gameshelf Proposal" or include the header "FSP Proposal before the links
- [x] ~Hopefully you'll be able to give it a proper name soon :)~ Change the repo name and the wiki main page to reflect the "Gameshelf" name used elsewhere in the wiki!

### MVP List
- [x] Include review deletion!
- [x] This might seem redundant, but you should include somewhere that every feature should have "Adequate styling, Smooth, bug-free navigation, and Adequate and appropriate seeds to demonstrate the feature"

### Schema
- [x] Might want to include a title for your reviews depending on how you plan to format your website. It's possible to go without, but the majority of review sites I know include a title.
- [x] Your reviews should include a rating column!!!!!!
- [x] If you specify bonuses here you should specify them in your MVP List under a Bonus header!

### Routes
- [x] Your routes are calling your app "Winterest" now? Probably just a mistake, haha, but make sure you stay consistent with the name you choose :)
- [x] Routes should be wrapped in `backticks`
- [x] Include a route for search!

### Sample State
- [x] The outer curly braces should be included in the code snippet.
- [x] The top line of your code snippet should be ```javascript to include syntax highlighting
- [x] Session should include your `current_user`

### Component Heirarchy
- [x] Be sure to include containers any place where you will be fetching data from the store! (Group show pages, Event pages, edit pages, etc)
- [x] Also, try to list out routes and preliminary ideas for state for components where that is relevant. Doesn't have to be perfect, just give it a first pass (also the routes should match your routes in the Routes section of your proposal, so make sure those are 1:1.)
- [x] Wrap component names in `backticks`

Feel free to reference the [BlueBird wiki](https://github.com/appacademy/bluebird/wiki) as an example of what I mean! Try your best to get this done tomorrow so that you can start right away!

**Comment by marshallycheng** [comment]
For the state in Game Show/Reviews, I wrote games[:id] and reviews[:id]. Would it just be games[:id] because the the reviews I'm accessing are all under the game's review ids?

**Comment by s-pangburn** [comment]
Depends entirely on how you have your state set up in the component! The simplest way would be for you to fetch reviews and games in the container under `store.games` and `store.reviews` (assuming a normalized state), so you'd probably create a selector to fetch reviews by `gameId`, and wouldn't need to include any logic to do that in the component itself.

In short, it depends how you implement it!

**Comment by s-pangburn** [comment]
On that note, this looks good! Feel free to start whenever you're ready 🙂
