### ISSUE TITLE
PA Review: Games 

### ISSUE THREAD

**Issue by marshallycheng** [marshallycheng/Gameshelf#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by s-pangburn** [comment]
Hi Marshall,

Looks good! We'll polish it up some more once you finish up reviews, but for the purposes of this MVP this is more than adequate :)
