### ISSUE TITLE
PA Review: Games Search #4

### ISSUE THREAD

**Issue by marshallycheng** [marshallycheng/Gameshelf#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by s-pangburn** [comment]
- [x] When I click a search result nothing happens??? 🤔

**Comment by s-pangburn** [comment]
:+1:
