### ISSUE TITLE
PA Review: Profiles #5 

### ISSUE THREAD

**Issue by marshallycheng** [marshallycheng/Gameshelf#5]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by s-pangburn** [comment]
- [x] The favorited games should be rows of 3. I'm aware Pinterest doesn't do this, but it would just look better imo. 
   - You might be able to get away with 4, but you'd have to move the "Favorited Games" header over to the left edge to compensate. Up to you.
- [x] Sometimes when I visit a profile, return to the index, and go to another game, the page is blank and I get this error: `Uncaught TypeError: Cannot read property 'image_url' of undefined`
  - This seems to happen especially if i use the Back button in my browser a lot.
  - Actually this is happening every time I navigate to a profile from a game show page, then press the back button in my browser. Might have something to do with needing to fetch data?

**Comment by s-pangburn** [comment]
💯
